import { Email } from './email.type';
import { draftsFolder, familyFolder, inboxFolder, sentFolder, workFolder } from '../folder';

export const mockEmails: Email[] = [
    // Inbox emails
    {
        id: 'clq1234567890email00000001',
        subject: 'Welcome to CalmMail',
        from: 'support@calmmail.com',
        to: ['user@example.com'],
        processedAt: new Date('2023-06-01T10:00:00Z'),
        body: 'Thank you for choosing CalmMail. We hope you enjoy our calm and focused email experience.',
        isDraft: false,
        cc: [],
        bcc: [],
        read: false,
        folderId: inboxFolder.id,
    },
    {
        id: 'clq1234567890email00000002',
        subject: 'Meeting Tomorrow',
        from: 'manager@company.com',
        to: ['user@example.com'],
        cc: ['team@company.com'],
        bcc: [],
        processedAt: new Date('2023-06-02T10:00:00Z'),
        body: "Let's meet tomorrow at 10 AM to discuss the project progress.",
        isDraft: false,
        read: true,
        folderId: inboxFolder.id,
    },
    {
        id: 'clq1234567890email00000003',
        subject: 'Vacation Plans',
        from: 'friend@personal.com',
        to: ['user@example.com'],
        cc: [],
        bcc: [],
        processedAt: new Date('2023-06-03T10:00:00Z'),
        body: 'Hey, I was thinking about our vacation plans. How about we go to the beach next month?',
        isDraft: false,
        read: false,
        folderId: inboxFolder.id,
    },

    // Sent emails
    {
        id: 'clq1234567890email00000004',
        subject: 'Re: Project Update',
        from: 'user@example.com',
        to: ['colleague@company.com'],
        cc: [],
        bcc: [],
        processedAt: new Date('2023-06-04T10:00:00Z'),
        body: "I've completed the tasks you assigned. Please review and let me know if any changes are needed.",
        isDraft: false,
        read: true,
        folderId: sentFolder.id,
    },
    {
        id: 'clq1234567890email00000005',
        subject: 'Dinner Invitation',
        from: 'user@example.com',
        to: ['friend1@personal.com', 'friend2@personal.com'],
        cc: [],
        bcc: [],
        processedAt: new Date('2023-06-05T10:00:00Z'),
        body: 'Would you like to join us for dinner this Saturday at 7 PM?',
        isDraft: false,
        read: true,
        folderId: sentFolder.id,
    },

    // Draft emails
    {
        id: 'clq1234567890email00000006',
        subject: 'Project Proposal',
        from: 'user@example.com',
        to: ['client@company.com'],
        cc: [],
        bcc: [],
        processedAt: new Date('2023-06-06T10:00:00Z'),
        body: 'Here is the project proposal we discussed. [DRAFT - NOT COMPLETE]',
        isDraft: true,
        read: true,
        folderId: draftsFolder.id,
    },

    // Work folder emails
    {
        id: 'clq1234567890email00000007',
        subject: 'Quarterly Report',
        from: 'finance@company.com',
        to: ['user@example.com'],
        cc: ['team@company.com'],
        bcc: [],
        processedAt: new Date('2023-06-07T10:00:00Z'),
        body: 'Please find attached the quarterly financial report.',
        isDraft: false,
        read: false,
        folderId: workFolder.id,
    },
    {
        id: 'clq1234567890email00000008',
        subject: 'New Project Opportunity',
        from: 'sales@company.com',
        to: ['user@example.com'],
        cc: [],
        bcc: [],
        processedAt: new Date('2023-06-08T10:00:00Z'),
        body: "We have a new project opportunity with a potential client. Let's discuss it in our next meeting.",
        isDraft: false,
        read: true,
        folderId: workFolder.id,
    },

    // Family folder emails
    {
        id: 'clq1234567890email00000009',
        subject: 'Family Reunion',
        from: 'relative@family.com',
        to: ['user@example.com'],
        cc: ['family@group.com'],
        bcc: [],
        processedAt: new Date('2023-06-09T10:00:00Z'),
        body: "We're planning a family reunion next month. Please let me know if you can attend.",
        isDraft: false,
        read: false,
        folderId: familyFolder.id,
    },
];
