name: CI

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install --no-cache
      - run: bunx cypress install
      - uses: nrwl/nx-set-shas@v4

      - run: bun ci:lint
      - run: bun ci:build
      - run: bun ci:test
      - run: bun ci:test-coverage-merge

      - name: Generate merged coverage report
        run: bun ci:generate-coverage-report

      - name: Extract coverage percentage
        id: coverage
        run: |
          COVERAGE=$(npx nyc report --reporter=text-summary --temp-dir=coverage | grep "Lines" | awk '{print $3}' | sed 's/%//')
          echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT

      - name: Create Coverage Badge
        if: github.ref == 'refs/heads/main'
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 5e5f0185a79b23d8609188502a8ce8af
          filename: coverage-badge.json
          label: Coverage
          message: ${{ steps.coverage.outputs.percentage }}%
          color: ${{ steps.coverage.outputs.percentage >= 80 && 'green' || steps.coverage.outputs.percentage >= 60 && 'yellow' || 'red' }}
