import {
    airplane,
    archive,
    arrowBack,
    briefcase,
    cash,
    documentTextOutline,
    folderOutline,
    mail,
    mailOutline,
    paperPlaneOutline,
    people,
    send,
    trashOutline,
} from 'ionicons/icons';

export const APP_ICONS = {
    mailOutline,
    paperPlaneOutline,
    documentTextOutline,
    trashOutline,
    folderOutline,
    briefcase,
    people,
    cash,
    airplane,
    archive,
    mail,
    send,
    arrowBack,
};
